# Generated by Django 4.1.3 on 2022-11-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_twitter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
